MvcApplication2/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication2.Models;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;

namespace MvcApplication2.Controllers
{
    public class EstudianteController : Controller
    {
        private UsersContext2 db = new UsersContext2();


        public ActionResult BuscarEnVacuna(Estudiante estudiante)
        {
            var estudiantes = from b in db.Estudiantes
                              select b;

            foreach (var b in estudiantes)
            {
                if (b.num_documento.Equals(estudiante.num_documento) || b.codigo.Equals(estudiante.codigo))
                {
                    estudiante = b;
                }

            }
            if (estudiante.estudianteId == 0)
            {
                return View(estudiante);
            }
            else
            {
                return RedirectToAction("../Vacuna/EsquemaVacunacion/" + estudiante.estudianteId);
            }
        }


        //
        // GET: /Estudiante/
        public ActionResult Buscar(Estudiante estudiante)
        {
            var estudiantes = from b in db.Estudiantes
                              select b;

            foreach (var b in estudiantes)
            {
                if (b.num_documento.Equals(estudiante.num_documento) || b.codigo.Equals(estudiante.codigo))
                {
                    estudiante = b;
                }

            }
            if (estudiante.estudianteId == 0)
            {
                return View(estudiante);
            }
            else
            {
                return RedirectToAction("../Estudiante/PersonalesDS/" + estudiante.estudianteId);
            }
        }
        public ActionResult Index()
        {
            var estudiantes = db.Estudiantes.Include(e => e.HojaVida).Include(e => e.Programa).Include(e => e.Rotacion);
            return View(estudiantes.ToList());
        }
        public ActionResult RotacionEstudiante(string searchString, int id = 0)
        {

            string rotacion = Request.Params["rotacion"];
            if (rotacion == null)
            {
                ViewBag.id = id;
            }
            else
            {
                Estudiante estudiante = db.Estudiantes.Find(id);
                estudiante.rotacionId = Convert.ToInt32(rotacion);
                Rotacion rotacionE = db.Rotacions.Find(Convert.ToInt32(rotacion));
                rotacionE.numero_estudiantes = rotacionE.numero_estudiantes + 1;
                estudiante.Rotacion = rotacionE;
                db.Entry(rotacionE).State = EntityState.Modified;
                db.SaveChanges();
                db.Entry(estudiante).State = EntityState.Modified;
                db.SaveChanges();

            }
            var estudiantes = from s in db.Estudiantes
                              select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                int ss = Convert.ToInt32(searchString);
                estudiantes = estudiantes.Where(s => s.codigo == ss);
            }


            return View(estudiantes.ToList());
        }
       
        public ActionResult ReporteEstudiante(string searchString, int id = 0)
        {

           
              

            
            var estudiantes = from s in db.Estudiantes
                              select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                int ss = Convert.ToInt32(searchString);
                estudiantes = estudiantes.Where(s => s.codigo == ss);
            }


            return View(estudiantes.ToList());
        }
        public ActionResult ReporteEstudianteA(int id = 0)
        {




            Estudiante estudiante = db.Estudiantes.Find(id);

            ReportDocument rptH = new ReportDocument();
            string strRptPath = System.Web.HttpContext.Current.Server.MapPath("~/reporteEstudiante.rpt");
            rptH.Load(strRptPath);


            var vacunas = from b in db.Vacunas
                              select b;
            List<Vacuna> listav = new List<Vacuna>();
       int i=0;

       foreach (var b in vacunas)
            {
                  if (b.fecha_vacunacion > DateTime.Now.Date.AddMonths(-20) && b.hojaVidaId==estudiante.hojaVidaId)
                                         
                  
                  {


                      listav.Add(b);
              
                  }

                i++;
            }
            rptH.Database.Tables[0].SetDataSource(listav.ToList());
     
            rptH.SetParameterValue("programa", estudiante.Programa.nombre);
            rptH.SetParameterValue("modalidad", estudiante.modalidad + "");
            rptH.SetParameterValue("semestre", estudiante.semestre + "");
            rptH.SetParameterValue("estadom", estudiante.estado_academico + "");



            rptH.SetParameterValue("tipodoc", estudiante.tipo_documento);
            rptH.SetParameterValue("numdoc", estudiante.num_documento);
            rptH.SetParameterValue("codigo", estudiante.codigo);
            rptH.SetParameterValue("genero", estudiante.HojaVida.genero + "");
            rptH.SetParameterValue("nombre", estudiante.HojaVida.primer_nombre+" "+estudiante.HojaVida.segundo_nombre);
            rptH.SetParameterValue("apellidos", estudiante.HojaVida.primer_apellido + " " + estudiante.HojaVida.segundo_apellido);
            rptH.SetParameterValue("fecha_nacimiento", estudiante.HojaVida.fecha_nacimiento + "");
            rptH.SetParameterValue("hemoclasificacion", estudiante.HojaVida.hemoclasificacion + "");
            rptH.SetParameterValue("dpto_procedencia", estudiante.HojaVida.departamento_procedencia + "");
            rptH.SetParameterValue("mun_procedencia", estudiante.HojaVida.municipio_procedencia + "");
            rptH.SetParameterValue("barrio_procedencia", estudiante.barrio_procedencia + "");
            rptH.SetParameterValue("dir_procedencia", estudiante.direccion_procedencia + "");
            rptH.SetParameterValue("dir_local", estudiante.HojaVida.direccion_manizales + "");
            rptH.SetParameterValue("image", estudiante.HojaVida.imagen_DI + "");


            rptH.SetParameterValue("tel_proc", estudiante.telefono_procedencia+"");
            rptH.SetParameterValue("tel_local", "");
            rptH.SetParameterValue("estado_civil", estudiante.HojaVida.estado_civil+"");
            rptH.SetParameterValue("num_hijos", estudiante.HojaVida.hijos + "");
            rptH.SetParameterValue("mail", estudiante.HojaVida.correo + "");

            rptH.SetParameterValue("num_cel", estudiante.HojaVida.num_celular + "");

            
            rptH.SetParameterValue("nombre_padre", estudiante.HojaVida.Familia.primer_nombre_padre + " " + estudiante.HojaVida.Familia.primer_apellido_padre + " " + estudiante.HojaVida.Familia.segundo_apellido_padre);
            rptH.SetParameterValue("direccion_padre", estudiante.HojaVida.Familia.direccion_padre + "");
            rptH.SetParameterValue("nombre_madre", estudiante.HojaVida.Familia.primer_nombre_madre + " " + estudiante.HojaVida.Familia.primer_apellido_madre + " " + estudiante.HojaVida.Familia.segundo_apellido_madre);
            rptH.SetParameterValue("direccion_madre", estudiante.HojaVida.Familia.direccion_madre + "");
            rptH.SetParameterValue("nombre_acudiente", estudiante.HojaVida.Familia.primer_nombre_acudiente + " " + estudiante.HojaVida.Familia.primer_apellido_acudiente + " " + estudiante.HojaVida.Familia.segundo_apellido_acudiente);
            rptH.SetParameterValue("direccion_acudiente", estudiante.HojaVida.Familia.direccion_acudiente + "");
          



            Stream stream = rptH.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);

            return File(stream, "application/pdf");

        }
        public ActionResult RotacionEstudiante2(string searchString, int id = 0)
        {

            string rotacion = Request.Params["rotacion"];
            if (rotacion == null)
            {
                ViewBag.id = id;
            }
            else
            {
                Estudiante estudiante = db.Estudiantes.Find(id);
                estudiante.rotacionId = Convert.ToInt32(rotacion);
                Rotacion rotacionE = db.Rotacions.Find(Convert.ToInt32(rotacion));
                rotacionE.numero_estudiantes = rotacionE.numero_estudiantes + 1;
                estudiante.Rotacion = rotacionE;
                db.Entry(rotacionE).State = EntityState.Modified;
                db.SaveChanges();
                estudiante.Rotacion = rotacionE;
                db.Entry(estudiante).State = EntityState.Modified;
                db.SaveChanges();

            }


            return RedirectToAction("RotacionEstudiante/" + rotacion);
        }
       
      
        public ActionResult Details(int id = 0)
        {
            Estudiante estudiante = db.Estudiantes.Find(id);
            if (estudiante == null)
            {
                return HttpNotFound();
            }
            return View(estudiante);
        }



        //
        // GET: /Estudiante/Create

        public ActionResult Create()
        {
            ViewBag.hojaVidaId = new SelectList(db.HojaVidas, "hojaVidaId", "primer_nombre");
            ViewBag.programaId = new SelectList(db.Programas, "programaId", "nombre");
            ViewBag.rotacionId = new SelectList(db.Rotacions, "rotacionId", "rotacionId");
            return View();
        }

        //
        // POST: /Estudiante/Create

        [HttpPost]


        [ValidateAntiForgeryToken]
        public ActionResult Create(Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                
                db.Estudiantes.Add(estudiante);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

MvcApplication2/Controllers/RotacionEstudianteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication2.Models;

namespace MvcApplication2.Controllers
{
    public class RotacionEstudianteController : Controller
    {
        private UsersContext2 db = new UsersContext2();

        //
        // GET: /RotacionEstudiante/

        public ActionResult Index()
        {
            var rotacionestudiantes = db.RotacionEstudiantes.Include(r => r.IPS_ESE).Include(r => r.Rotacion).Include(r => r.Docente).Include(r => r.Estudiante);
            return View(rotacionestudiantes.ToList());
        }

        //
        // GET: /RotacionEstudiante/Details/5

        public ActionResult Details(int id = 0)
        {
            RotacionEstudiante rotacionestudiante = db.RotacionEstudiantes.Find(id);
            if (rotacionestudiante == null)
            {
                return HttpNotFound();
            }
            return View(rotacionestudiante);
        }

        //
        // GET: /RotacionEstudiante/Create

        public ActionResult Create()
        {
            ViewBag.IPS_ESEId = new SelectList(db.IPS_ESE, "IPS_ESEId", "origen");
            ViewBag.rotacionId = new SelectList(db.Rotacions, "rotacionId", "grupo");
            ViewBag.docenteId = new SelectList(db.Docentes, "docenteId", "tipo_documento");
            ViewBag.estudianteId = new SelectList(db.Estudiantes, "estudianteId", "tipo_documento");
            return View();
        }

        //
        // POST: /RotacionEstudiante/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RotacionEstudiante rotacionestudiante)
        {
            if (ModelState.IsValid)
            {
                db.RotacionEstudiantes.Add(rotacionestudiante);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IPS_ESEId = new SelectList(db.IPS_ESE, "IPS_ESEId", "origen", rotacionestudiante.IPS_ESEId);
            ViewBag.rotacionId = new SelectList(db.Rotacions, "rotacionId", "grupo", rotacionestudiante.rotacionId);
            ViewBag.docenteId = new SelectList(db.Docentes, "docenteId", "tipo_documento", rotacionestudiante.docenteId);
            ViewBag.estudianteId = new SelectList(db.Estudiantes, "estudianteId", "tipo_documento", rotacionestudiante.estudianteId);
            return View(rotacionestudiante);
        }

        //
        // GET: /RotacionEstudiante/Edit/5

        public ActionResult Edit(int id = 0)
        {
            RotacionEstudiante rotacionestudiante = db.RotacionEstudiantes.Find(id);
            if (rotacionestudiante == null)
            {
                return HttpNotFound();
            }
            ViewBag.IPS_ESEId = new SelectList(db.IPS_ESE, "IPS_ESEId", "origen", rotacionestudiante.IPS_ESEId);
            ViewBag.rotacionId = new SelectList(db.Rotacions, "rotacionId", "grupo", rotacionestudiante.rotacionId);
            ViewBag.docenteId = new SelectList(db.Docentes, "docenteId", "tipo_documento", rotacionestudiante.docenteId);
            ViewBag.estudianteId = new SelectList(db.Estudiantes, "estudianteId", "tipo_documento", rotacionestudiante.estudianteId);
            return View(rotacionestudiante);
        }

        //
        // POST: /RotacionEstudiante/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RotacionEstudiante rotacionestudiante)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rotacionestudiante).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IPS_ESEId = new SelectList(db.IPS_ESE, "IPS_ESEId", "origen", rotacionestudiante.IPS_ESEId);
            ViewBag.rotacionId = new SelectList(db.Rotacions, "rotacionId", "grupo", rotacionestudiante.rotacionId);
            ViewBag.docenteId = new SelectList(db.Docentes, "docenteId", "tipo_documento", rotacionestudiante.docenteId);
            ViewBag.estudianteId = new SelectList(db.Estudiantes, "estudianteId", "tipo_documento", rotacionestudiante.estudianteId);
            return View(rotacionestudiante);
        }

        //
        // GET: /RotacionEstudiante/Delete/5

        public ActionResult Delete(int id = 0)
        {
            RotacionEstudiante rotacionestudiante = db.RotacionEstudiantes.Find(id);
            if (rotacionestudiante == null)
            {
                return HttpNotFound();
            }
            return View(rotacionestudiante);
        }

        //
        // POST: /RotacionEstudiante/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RotacionEstudiante rotacionestudiante = db.RotacionEstudiantes.Find(id);
            db.RotacionEstudiantes.Remove(rotacionestudiante);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcApplication2/Views/Estudiante/Academicos.cshtml
@model MvcApplication2.Models.Estudiante

    <div class="row">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Datos Personales", "Personales/" + Model.estudianteId, "Estudiante")</li>
                        <li>@Html.ActionLink("Información Familiar", "Familiares/" + Model.estudianteId, "Estudiante")</li>
                        <li>@Html.ActionLink("Datos Académicos", "Academicos/" + Model.estudianteId, "Estudiante")</li>
                        <li>@Html.ActionLink("Carné de Vacunación", "CarnetVacunacion/" + Model.estudianteId, "Estudiante")</li>
                        <li>@Html.ActionLink("Afiliación a Salud", "Salud/" + Model.estudianteId, "Estudiante")</li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>



    <div class="container">
        <div class="row">
            <fieldset>
                <legend>Información Académica</legend>
                <div class="well">
                    <div class="container">
                        <div class="col-sm-3">
                            <img src="@Url.Content(Model.HojaVida.imagen_DI)" alt="..." class="img-rounded"><br />
   </div>

                        <div class="col-sm-8">

                            <div class="row">
                                <form class="form-horizontal" role="form">

                                    <!-- Text input-->

                                    <div class="form-group">

                                        <label class="col-sm-2 control-label">Programa</label>
                                        <div class="col-sm-4">
                                            @Html.TextBoxFor(model => model.Programa.nombre, new { @class = "form-control", @readonly = "readonly" })
                                        </div>
                                        <label class="col-sm-2 control-label">Modalidad</label>
                                        <div class="col-sm-4">
                                            @Html.TextBoxFor(model => model.Programa.modalidad, new { @class = "form-control", @readonly = "readonly" })
                                        </div>
                                    </div>
                                                                                                           
                                    <div class="form-group">

                                        <label class="col-sm-2 control-label">Semestre</label>
                                        <div class="col-sm-4">
                                            @Html.TextBoxFor(model => model.semestre, new { @class = "form-control", @readonly = "readonly" })
                                        </div>


                                        <label class="col-sm-2 control-label">Estado</label>
                                        <div class="col-sm-4">
                                            @Html.TextBoxFor(model => model.estado_academico, new { @class = "form-control", @readonly = "readonly" })
                                        </div>

                                    </div>
                                    
                            </div>
                            </div>



                            </form>
                        </div><!-- /.row -->
                    </div>
            </fieldset>
         






            </div>
        </div>

MvcApplication2/Views/Estudiante/CarnetVacunacion.cshtml
@model MvcApplication2.Models.Estudiante
<script>
    $(document).ready(function () {
        $("#submitButton").on("click", function () {
            alert('Your Message');
        });

    });

</script>




<div class="row">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Datos Personales", "Personales/" + Model.estudianteId, "Estudiante")</li>
                    <li>@Html.ActionLink("Información Familiar", "Familiares/" + Model.estudianteId, "Estudiante")</li>
                    <li>@Html.ActionLink("Datos Académicos", "Academicos/" + Model.estudianteId, "Estudiante")</li>
                    <li>@Html.ActionLink("Carné de Vacunación", "CarnetVacunacion/" + Model.estudianteId, "Estudiante")</li>
                    <li>@Html.ActionLink("Afiliación a Salud", "Salud/" + Model.estudianteId, "Estudiante")</li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>

@using (Html.BeginForm("Personales", "Estudiante", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="container">
        <div class="row">
            <fieldset>
                

                <!-- /.navbar-collapse aca va leyend -->


                

                <div class="col-sm-8">

                    <div class="row">

                        <!-- Text input-->

                        <fosrm class="form-horizontal" role="form">


                            


                            

                         



                            @*<div class="form-group">
                                <div class="col-sm-4">

                                    <br>

                                    <br>
                                    <br>
                                </div>
                            </div>*@

                            <div class="table-responsive">
                                <table class="table">

                                    <tr>
                                        <th>Vacuna</th>
                                        <th>Fecha Vacunacion</th>
                                       
                                        <th>Fecha Proxima Vacunacion</th>
                                        
                                    </tr>
                                    @for (var i = 0; i < Model.HojaVida.Vacunas.Count; i++)
                                    {

                                        <tr>
 
                                            <th>@Html.DisplayFor(m => Model.HojaVida.Vacunas.ElementAt(i).nombre_generico)</th>
                                          @if (Model.HojaVida.Vacunas.ElementAt(i).fecha_vacunacion > DateTime.Now.Date.AddMonths(-20))
                                          {
                                              <th>@Html.DisplayFor(m => Model.HojaVida.Vacunas.ElementAt(i).fecha_vacunacion)</th>
                                    <th>@Html.DisplayFor(m => Model.HojaVida.Vacunas.ElementAt(i).fecha_prox_vacunacion)</th>


                                          }
                                          else
                                          {

                                          }





                                        </tr>
                                    }

                                </table>
                            </div>

                            </div>

                </div><!-- /.row -->



                <div class="col-sm-3">

                </div>


                <div class="col-sm-8">
                    <div class="row">
                        <fdorm class="form-horizontal" role="form">


                            








                          
                        </fdorm>

                    </div><!-- /.row -->
                </div>
            </fieldset>
        </div>
    </div>







}

MvcApplication2/Views/Estudiante/Familiares.cshtml
@model MvcApplication2.Models.Estudiante



    <div class="row">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Datos Personales", "Personales/" + Model.estudianteId, "Estudiante")</li>
                        <li>@Html.ActionLink("Información Familiar", "Familiares/" + Model.estudianteId, "Estudiante")</li>
                        <li>@Html.ActionLink("Datos Académicos", "Academicos/" + Model.estudianteId, "Estudiante")</li>
                        <li>@Html.ActionLink("Carné de Vacunación", "CarnetVacunacion/" + Model.estudianteId, "Estudiante")</li>
                        <li>@Html.ActionLink("Afiliación a Salud", "Salud/" + Model.estudianteId, "Estudiante")</li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>

@*<legend>Datos Familiares</legend>*@
<div class="container">
    <div class="row">
        <fieldset>
            <legend>Datos Familiares</legend>

            <table class="table table-striped table-hover">

                <tr>
                    <th>Parentesco</th>
                    <th>Primer Nombre</th>
                    <th>Segundo Nombre</th>
                    <th>Primer Apellido</th>
                    <th>Segundo Apellido</th>
                    <th>Dirección</th>
                    <th>Teléfono</th>
                </tr>
                <tr>
                    <th>Padre</th>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.primer_nombre_padre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.segundo_nombre_padre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.primer_apellido_padre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.segundo_apellido_padre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.direccion_padre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.telefono_padre)</td>
                </tr>
                <tr>
                    <th>Madre</th>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.primer_nombre_madre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.segundo_nombre_madre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.primer_apellido_madre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.segundo_apellido_madre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.direccion_madre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.telefono_madre)</td>
                </tr>
                <tr>
                    <th>Acudiente</th>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.primer_nombre_acudiente)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.segundo_nombre_acudiente)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.primer_apellido_acudiente)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.segundo_apellido_acudiente)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.direccion_acudiente)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.telefono_acudiente)</td>
                </tr>
            </table>
            


                        <!-- Text input-->





        </fieldset>
    </div>
</div>

MvcApplication2/Views/Estudiante/FamiliaresDS.cshtml
@model MvcApplication2.Models.Estudiante



    <div class="row">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Datos Personales", "PersonalesDS/" + Model.estudianteId, "Estudiante")</li>
                        <li>@Html.ActionLink("Información Familiar", "FamiliaresDS/" + Model.estudianteId, "Estudiante")</li>
                        <li>@Html.ActionLink("Datos Académicos", "AcademicosDS/" + Model.estudianteId, "Estudiante")</li>
                        <li>@Html.ActionLink("Carné de Vacunación", "CarnetVacunacionDS/" + Model.estudianteId, "Estudiante")</li>
                        <li>@Html.ActionLink("Afiliación a Salud", "SaludDS/" + Model.estudianteId, "Estudiante")</li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>

@*<legend>Datos Familiares</legend>*@
<div class="container">
    <div class="row">
        <fieldset>
            <legend>Datos Familiares</legend>

            <table class="table table-striped table-hover">

                <tr>
                    <th>Parentesco</th>
                    <th>Primer Nombre</th>
                    <th>Segundo Nombre</th>
                    <th>Primer Apellido</th>
                    <th>Segundo Apellido</th>
                    <th>Dirección</th>
                    <th>Teléfono</th>
                </tr>
                <tr>
                    <th>Padre</th>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.primer_nombre_padre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.segundo_nombre_padre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.primer_apellido_padre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.segundo_apellido_padre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.direccion_padre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.telefono_padre)</td>
                </tr>
                <tr>
                    <th>Madre</th>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.primer_nombre_madre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.segundo_nombre_madre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.primer_apellido_madre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.segundo_apellido_madre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.direccion_madre)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.telefono_madre)</td>
                </tr>
                <tr>
                    <th>Acudiente</th>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.primer_nombre_acudiente)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.segundo_nombre_acudiente)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.primer_apellido_acudiente)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.segundo_apellido_acudiente)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.direccion_acudiente)</td>
                    <td>@Html.DisplayFor(model => model.HojaVida.Familia.telefono_acudiente)</td>
                </tr>
            </table>
            


                        <!-- Text input-->





        </fieldset>
    </div>
</div>